name: Payer
version: '${project.version}'
main: PayerPlugin
authors: [Waterbroodje]
description: With Payer, you can create and manage real payments directly from your Minecraft Server.
commands:
  payer:
    aliases: [pay, payer]
    description: The command for players and admins to interact with the plugin.
